services:
  postgresDataBase:
    image: postgres:17.2
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: betterStudy
    #      POSTGRES_USERNAME: postgres
    restart: always
    ports:
      - "5433:5432"

#  maildevim:
#    image: maildev/maildev

  maildev:
    container_name: maildev
    image: maildev/maildev
    restart: always
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1080:1080"
      - "1025:1025"

# TODO run container maildev
